name: mysimplenote
description: "MySimpleNote is a personal notes management application for organizing daily notes."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+4
  path: ^1.8.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0  # Correct package for launcher icons
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:  # Configuration for flutter_launcher_icons
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # Correct path to your app icon

flutter:
  uses-material-design: true
  assets:
    - assets/icon/  # Ensure the assets folder is declared correctly

